package com.campus.issue_tracker.service;

import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

/**
 * Syncs translations from English to Sinhala and Tamil using the Translation API.
 * Reads messages_en.properties, translates each value, and writes messages_si.properties and messages_ta.properties.
 */
@Service
public class TranslationSyncService {

    private final TranslationApiService translationApiService;

    public TranslationSyncService(TranslationApiService translationApiService) {
        this.translationApiService = translationApiService;
    }

    /**
     * Sync all messages from English to Sinhala and Tamil.
     * Writes to src/main/resources/i18n/ (relative to working directory).
     */
    public SyncResult syncAll() {
        if (!translationApiService.isAvailable()) {
            return SyncResult.failed("Translation API is not configured. Set translation.api.key and translation.api.enabled=true in application.properties");
        }

        try {
            Properties enProps = loadProperties("i18n/messages_en.properties");
            if (enProps.isEmpty()) {
                return SyncResult.failed("Could not load messages_en.properties");
            }

            Properties siProps = new Properties();
            Properties taProps = new Properties();

            int count = 0;
            for (String key : enProps.stringPropertyNames()) {
                String value = enProps.getProperty(key);
                if (value == null || value.isBlank() || value.startsWith("#")) continue;

                try {
                    String si = translationApiService.translate(value, "si");
                    String ta = translationApiService.translate(value, "ta");
                    siProps.setProperty(key, si);
                    taProps.setProperty(key, ta);
                    count++;

                    // Rate limit: avoid hitting API too fast (free tier allows 100 requests/100 sec)
                    Thread.sleep(100);
                } catch (Exception e) {
                    // Keep original on translation failure
                    siProps.setProperty(key, value);
                    taProps.setProperty(key, value);
                }
            }

            Path basePath = Path.of(System.getProperty("user.dir"), "src", "main", "resources", "i18n");
            Files.createDirectories(basePath);

            saveProperties(basePath.resolve("messages_si.properties"), siProps);
            saveProperties(basePath.resolve("messages_ta.properties"), taProps);

            return SyncResult.success(count);
        } catch (Exception e) {
            return SyncResult.failed(e.getMessage());
        }
    }

    private Properties loadProperties(String classpathPath) throws IOException {
        Properties props = new Properties();
        try (InputStream in = new ClassPathResource(classpathPath).getInputStream()) {
            props.load(new InputStreamReader(in, StandardCharsets.UTF_8));
        }
        return props;
    }

    private void saveProperties(Path path, Properties props) throws IOException {
        try (OutputStream out = Files.newOutputStream(path);
             Writer writer = new OutputStreamWriter(out, StandardCharsets.UTF_8)) {
            props.store(writer, "Auto-generated by Translation API - " + new Date());
        }
    }

    public record SyncResult(boolean success, String message, int translatedCount) {
        static SyncResult success(int count) {
            return new SyncResult(true, "Translated " + count + " keys to Sinhala and Tamil", count);
        }
        static SyncResult failed(String msg) {
            return new SyncResult(false, msg, 0);
        }
    }
}
